name : ETL pipeline

on:
    push:
        branches:
            - main

jobs:
    
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job1.py
              run: python job1.py

    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job2.py
              run: python job2.py

    job3:
        needs : job1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job3.py
              run: python job3.py

    job4:
        needs : job2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job4.py
              run: python job4.py

    job5:
        needs : job3
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job5.py
              run: python job5.py

    job6:
        needs : [job4,job5]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run job6.py
              run: python job6.py